[package]
name = "shinyaic_wasm"
version = "0.1.0"
authors = ["shinyaigeek <PhilisPaxil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
shinyaic_core = { path = "../shinyaic_core" }
wasm-bindgen = "0.2.78"
js-sys = "0.3.55"

[dependencies.web-sys]
version = "0.3.55"
features = [
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'HtmlDivElement',
  'CssStyleDeclaration',
  'Window',
  'TextMetrics',
]